language: ruby
cache:
  bundler: true
  yarn: true
addons:
  postgresql: '9.6'
before_install:
  - nvm install --lts
before_script:
  - psql -c 'create database home_improvement_test;' -U postgres
script:
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - SECRET_KEY_BASE=a RAILS_ENV=production bundle exec rake assets:precompile
  - bundle exec rake